# Generated by Django 3.2.19 on 2023-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0023_auto_20230930_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='billdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
