# Generated by Django 3.2.19 on 2023-10-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_projectfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.project1')),
            ],
        ),
    ]
