# Generated by Django 3.2.19 on 2023-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project1',
            name='mode',
            field=models.CharField(default='Active', max_length=200),
        ),
    ]
